build_image:
  script:
    - docker login -u="$GIT_USER" -p="$GIT_PASS"
    - "docker build -t roadtripfinder:build ."
    - "docker tag roadtripfinder:build jc6482/roadtripfinder:latest"
    - "docker push jc6482/roadtripfinder:latest"
    - "docker rmi -f roadtripfinder:build jc6482/roadtripfinder:latest || true"
    - docker logout

sonar_scan:
  script:
    - mvn clean install sonar:sonar -Dsonar.host.url=http://10.64.0.5:30900 -Dsonar.login=$SONAR_TOKEN 

kube_deploy:
  script:
    - /usr/bin/kubectl apply --validate=true --filename=deployment.yaml
